language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev

before_script:
- |
  if [ "${TRAVIS_OS_NAME}" = 'osx' ]; then
    export PATH=$HOME/Library/Python/2.7/bin:$PATH
    export KCOV=""
  else
    export PATH=$HOME/.local/bin:$PATH
    export KCOV="${TRAVIS_BUILD_DIR}/kcov/build/src/kcov --exclude-pattern=/.cargo --coveralls-id=${TRAVIS_JOB_ID} ${TRAVIS_BUILD_DIR}/coverage"
  fi
- |
  if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    wget https://github.com/SimonKagstrom/kcov/archive/master.zip
    unzip master.zip
    mv kcov-master kcov
    mkdir kcov/build
    cd kcov/build
    cmake ..
    make
    cd ${TRAVIS_BUILD_DIR}
  fi

script:
- cargo build
- cargo test --release
- cargo test --no-run
- ${KCOV} ./target/debug/deps/chfft-*
- if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo bench --release --verbose
  fi

after_success:
- |
  if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    travis-cargo --only stable doc-upload
  fi
