language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
#  - osx

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - libiberty-dev

before_script:
- |
  if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    cargo install cargo-kcov
    cargo kcov --print-install-kcov-sh | sh
  fi

script:
- cargo build
- |
  if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    cargo kcov --coveralls
  else
    cargo test
  fi
- cargo test --release
- |
  if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
    cargo bench --verbose
  fi

after_success:
- |
  if [ "${TRAVIS_OS_NAME}" = "linux" ] &&
     [ "${TRAVIS_RUST_VERSION}" = "stable" ] &&
     [ "${TRAVIS_BRANCH}" = "master" ] &&
     [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    pip install 'ghp-import' --user
    ghp-import -n target/doc
    git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
  fi
