language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
- if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo bench --verbose;
  fi

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev

before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH

after_success:
- travis-cargo --only stable doc-upload
- |
  if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
    wget https://github.com/SimonKagstrom/kcov/archive/v33.tar.gz &&
    tar xzf v33.tar.gz && mkdir kcov-33/build && cd kcov-33/build &&
    cmake -DCMAKE_INSTALL_PREFIX=~/.local .. && make &&
    make install &&
    cd ../.. &&
    ~/.local/bin/kcov --verify \
        --coveralls-id=$TRAVIS_JOB_ID \
        --exclude-pattern=/.cargo \
        target/kcov target/debug/chfft-*
  fi
