[package]
name = "chfft"
version = "0.1.1"
authors = ["Mitsuharu Seki <mitsu1986@gmail.com>"]
repository = "https://github.com/chalharu/chfft"
keywords = ["fft", "numerics", "dsp", "mathematics"]
license = "MPL-2.0"
readme = "README.md"
description = "Chalharu's Fastest Fourier Transform library."
documentation = "https://chalharu.github.io/chfft/chfft/"

[dependencies]
num-traits = "0.1.40"
num = "0.1.40"

[dev-dependencies]
rand = "0.3.16"
