[package]
name = "chfft"
version = "0.1.0"
authors = ["Mitsuharu Seki <mitsu1986@gmail.com>"]
repository = "https://github.com/chalharu/chfft"
keywords = ["fft", "numerics", "dsp", "mathematics"]
license-file = "LICENSE.md"
readme = "README.md"
description = "Chalharu's Fastest Fourier Transform library."
documentation = https://chalharu.github.io/chfft/

[dependencies]
num-traits = "*"
num = "*"

[dev-dependencies]
rand = "*"
